require('humanoid.settings')
require('humanoid.packer')
require('humanoid.lsp')
require('humanoid.cmp')
require('humanoid.treesitter')
require('humanoid.lualine')
require('humanoid.auto-pairs')
require('humanoid.impatient')
require('humanoid.telescope')

